# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  # Update Python deps for the template (not the generated project)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  # Update npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  # Update template npm packages
  - package-ecosystem: "npm"
    directory: "template/{{dkcutter.projectSlug}}/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/local/django/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/local/node/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/production/aws/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/production/django/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/production/postgres/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "docker"
    directory: "template/{{dkcutter.projectSlug}}/compose/production/traefik/"
    schedule:
      interval: "daily"
    labels:
      - "dependency update"
    commit-message:
      include: scope
      prefix: chore
