log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'
    http:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ':443'
  {%- if dkcutter.useCelery %}

  flower:
    address: ':5555'
  {%- endif %}

certificatesResolvers:
  letsencrypt:
    # https://doc.traefik.io/traefik/https/acme/#lets-encrypt
    acme:
      email: '{{ dkcutter.email }}'
      storage: /etc/traefik/acme/acme.json
      # https://doc.traefik.io/traefik/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      {%- if dkcutter.domainName|wordCount('.') == 1 %}
      rule: 'Host(`{{ dkcutter.domainName }}`) || Host(`www.{{ dkcutter.domainName }}`)'
      {%- else %}
      rule: 'Host(`{{ dkcutter.domainName }}`)'
      {%- endif %}
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        certResolver: letsencrypt
    {%- if dkcutter.useCelery %}

    flower-secure-router:
      rule: 'Host(`{{ dkcutter.domainName }}`)'
      entryPoints:
        - flower
      service: flower
      tls:
        # https://doc.traefik.io/traefik/master/routing/routers/#certresolver
        certResolver: letsencrypt
    {%- endif %}
    {%- if dkcutter.cloudProvider == 'None' %}

    web-media-router:
      {%- if dkcutter.domainName|wordCount('.') == 1 %}
      rule: '(Host(`{{ dkcutter.domainName }}`) || Host(`www.{{ dkcutter.domainName }}`)) && PathPrefix(`/media/`)'
      {%- else %}
      rule: 'Host(`{{ dkcutter.domainName }}`) && PathPrefix(`/media/`)'
      {%- endif %}
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt
    {%- endif %}

  middlewares:
    csrf:
      # https://doc.traefik.io/traefik/master/middlewares/http/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000
    {%- if dkcutter.useCelery %}

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555
    {%- endif %}
    {%- if dkcutter.cloudProvider == 'None' %}

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80
    {%- endif %}

providers:
  # https://doc.traefik.io/traefik/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
