version: "3.8"

volumes:
  {{ projectSlug }}_local_postgres_data: {}
  {{ projectSlug }}_local_postgres_data_backups: {}

services:
  django:{% if useCelery %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ projectSlug }}_local_django
    container_name: {{ projectSlug }}_local_django
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    ports:
      - 8000:8000
    volumes:
      - .:/app:z
    depends_on:
      - postgres
      {%- if useCelery %}
      - redis
      {%- endif %}
      {%- if useMailpit %}
      - mailpit
      {%- endif %}
    command: "/start"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ projectSlug }}_production_postgres
    container_name: {{ projectSlug }}_local_postgres
    volumes:
      - {{ projectSlug }}_local_postgres_data:/var/lib/postgresql/data
      - {{ projectSlug }}_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  {%- if useMailpit %}

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: {{ projectSlug }}_local_mailpit
    ports:
      - "8025:8025"

  {%- endif %}
  {%- if useCelery %}

  redis:
    image: redis:6
    container_name: {{ projectSlug }}_local_redis

  celeryworker:
    <<: *django
    image: {{ projectSlug }}_local_celeryworker
    container_name: {{ projectSlug }}_local_celeryworker
    depends_on:
      - redis
      - postgres
      {%- if useMailpit %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ projectSlug }}_local_celerybeat
    container_name: {{ projectSlug }}_local_celerybeat
    depends_on:
      - redis
      - postgres
      {%- if useMailpit %}
      - mailpit
      {%- endif %}
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ projectSlug }}_local_flower
    container_name: {{ projectSlug }}_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  {%- endif %}
  {%- if useTailwindcss %}

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: {{ projectSlug }}_local_node
    container_name: {{ projectSlug }}_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev

  {%- endif %}
  {%- if usePgadmin %}

  pg_admin:
    image: dpage/pgadmin4
    container_name: {{ projectSlug }}_local_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@email.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80

  {%- endif %}
