# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: github-actions
    directory: /
    # Every weekday
    schedule:
      interval: daily

  # Enable version updates for Docker
  - package-ecosystem: docker
    # Look for a `Dockerfile` in the `compose/local/django` and `compose/production/django` directory
    directories:
      - "compose/local/django/"
      - "compose/production/django/"
    # Every weekday
    schedule:
      interval: daily
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: "docker.io/python"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: docker
    directories:
{%- if dkcutter.frontendPipeline != "None" %}
      - "compose/local/node/"
{%- endif %}
{%- if dkcutter.cloudProvider == "AWS" %}
      - "compose/production/aws/"
{%- endif %}
      - "compose/production/postgres/"
      - "compose/production/traefik/"
{%- if dkcutter.cloudProvider == "None" %}
      - "compose/production/nginx/"
{%- endif %}
    # Every weekday
    schedule:
      interval: daily

{%- if dkcutter.frontendPipeline != "None" %}

  # Enable version updates for javascript/npm
  - package-ecosystem: npm
    # Look for a `packages.json` in the `root` directory
    directory: /
    # Every weekday
    schedule:
      interval: daily

{%- endif %}

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: pip
    # Look for a `requirements.txt` in the `root` directory
    # also `setup.cfg`, `.python-version` and `requirements/*.txt`
    directory: /
    # Every weekday
    schedule:
      interval: daily
