name: CI

on:
  push:
    branches: [master, main]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-code:
    name: Check Code - CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Check code
        run: pnpm check

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    name: "test ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 18
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Node dependencies
        run: pnpm install
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pnpm test

  docker:
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: Basic
            args: ""
          - name: Celery & DRF
            args: --useCelery --restFramework DRF
          - name: Celery & DNRF
            args: --useCelery --restFramework DNRF
          - name: TailwindCSS
            args: --useTailwindcss

    name: "Docker ${{ matrix.script.name }}"
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 18
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Node dependencies
        run: pnpm install
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Docker ${{ matrix.script.name }}
        run: sh tests/test_docker.sh ${{ matrix.script.args }}
